The ''7-base_geometry'' module
==============================

Using ''BaseGeometry''
----------------------

Importing function from the module:
    >>> BaseGeometry = __import__("7-base_geometry").BaseGeometry

Check for module docstring:
    >>> m = __import__("7-base_geometry").__doc__
    >>> len(m) > 1
    True

Check for class docstring:
    >>> c = __import__("7-base_geometry").BaseGeometry.__doc__
    >>> len(c) > 1
    True

Check for methods docstring:
    >>> met1 = __import__("7-base_geometry").BaseGeometry.area.__doc__
    >>> len(met1) > 1
    True
    >>> met2 = __import__("7-base_geometry").BaseGeometry.integer_validator.__doc__
    >>> len(met2) > 1
    True

Check for area method:
    >>> b = BaseGeometry()
    >>> b.area()
    Traceback (most recent call last):
    ...
    Exception: area() is not implemented

Check for integer_validator method:
    >>> b.integer_validator("integer", 1)

Check for integer_validator with an 0 int:
    >>> b.integer_validator("integer", 0)
    Traceback (most recent call last):
    ...
    ValueError: integer must be greater than 0

Check for integer_validator with non-integer types:
    >>> b.integer_validator("bool", True)
    Traceback (most recent call last):
    ...
    TypeError: bool must be an integer
    >>> b.integer_validator("list", [1, 2, 3])
    Traceback (most recent call last):
    ...
    TypeError: list must be an integer
    >>> b.integer_validator("float", 5.5)
    Traceback (most recent call last):
    ...
    TypeError: float must be an integer
    >>> b.integer_validator("string", "hello")
    Traceback (most recent call last):
    ...
    TypeError: string must be an integer
    >>> b.integer_validator("tuple", (1, 2))
    Traceback (most recent call last):
    ...
    TypeError: tuple must be an integer

Check for no arguments on integer_validator:
    >>> b.integer_validator()
    Traceback (most recent call last):
    ...
    TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

Check for only one argument on integer_validator:
    >>> b.integer_validator("integer")
    Traceback (most recent call last):
    ...
    TypeError: integer_validator() missing 1 required positional argument: 'value'

Check for more than two arguments on integer_validator:
    >>> b.integer_validator("integer", 1, 2)
    Traceback (most recent call last):
    ...
    TypeError: integer_validator() takes 3 positional arguments but 4 were given
